# Generated by Django 3.2.9 on 2022-01-22 02:04

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ideologistFlag', models.BooleanField(default=False)),
                ('builderFlag', models.BooleanField(default=False)),
                ('profilePicture', models.ImageField(default='', upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Builder',
            },
        ),
        migrations.CreateModel(
            name='Ideologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ideologist',
            },
        ),
        migrations.CreateModel(
            name='InterestProjectBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectalo.builder')),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('interestRating', models.IntegerField()),
                ('budget', models.FloatField()),
                ('timeBurden', models.IntegerField()),
                ('stage', models.IntegerField(choices=[(1, 'Rough'), (2, 'Shaped'), (3, 'Polished'), (4, 'Jewel')])),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.IntegerField(choices=[(1, 'Immaterial'), (2, 'Tangible'), (3, 'Solid'), (4, 'Powerful')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectalo.builder')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proyectalo.technology')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialDate', models.DateField(default=None)),
                ('endDate', models.DateField(default=None)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proyectalo.builder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectalo.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='builders',
            field=models.ManyToManyField(related_name='projBuild', through='proyectalo.ProjectBuilder', to='proyectalo.Builder'),
        ),
        migrations.AddField(
            model_name='project',
            name='ideologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectalo.ideologist'),
        ),
        migrations.AddField(
            model_name='project',
            name='interested',
            field=models.ManyToManyField(related_name='IntProjBuil', through='proyectalo.InterestProjectBuilder', to='proyectalo.Builder'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='proyectalo.Technology'),
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectalo.locality')),
                ('zipCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectalo.zipcode')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default="Hi! I'm sending you this message")),
                ('date', models.DateTimeField(default=None)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiverUser', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='senderUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectalo.builder')),
                ('ideologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectalo.ideologist')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proyectalo.project')),
            ],
        ),
        migrations.AddField(
            model_name='locality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectalo.state'),
        ),
        migrations.AddField(
            model_name='interestprojectbuilder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectalo.project'),
        ),
        migrations.AddField(
            model_name='builder',
            name='technologies',
            field=models.ManyToManyField(through='proyectalo.TechnologyBuilder', to='proyectalo.Technology'),
        ),
        migrations.AddField(
            model_name='builder',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('apartment', models.CharField(max_length=1)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectalo.neighborhood')),
            ],
        ),
    ]
