# Generated by Django 3.2.9 on 2022-01-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectalo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='offererFlag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='seekerFlag',
            field=models.BooleanField(default=False),
        ),
    ]
