# Generated by Django 3.2.9 on 2022-01-22 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectalo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technologybuilder',
            old_name='project',
            new_name='builder',
        ),
    ]
