# Generated by Django 3.2.9 on 2022-01-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectalo', '0002_auto_20220119_0329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offerer',
            new_name='Builder',
        ),
        migrations.RenameModel(
            old_name='Seeker',
            new_name='Ideologist',
        ),
        migrations.AlterModelOptions(
            name='builder',
            options={'verbose_name': 'Builder'},
        ),
        migrations.AlterModelOptions(
            name='ideologist',
            options={'verbose_name': 'Ideologist'},
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='offerer',
            new_name='builder',
        ),
    ]
