# Generated by Django 3.2.9 on 2022-01-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectalo', '0002_rename_project_technologybuilder_builder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technologie'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='builderFlag',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ideologistFlag',
        ),
        migrations.AddField(
            model_name='user',
            name='job_type',
            field=models.IntegerField(choices=[(1, 'Ideologist'), (2, 'Builder')], default=1),
            preserve_default=False,
        ),
    ]
