# Generated by Django 3.2.9 on 2022-01-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectalo', '0003_auto_20220120_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='offererFlag',
        ),
        migrations.AddField(
            model_name='user',
            name='ideologistFlag',
            field=models.BooleanField(default=False),
        ),
    ]
