# Generated by Django 3.2.9 on 2022-01-20 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectalo', '0005_rename_seekerflag_user_builderflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Interest',
            new_name='InterestProjectBuilder',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='ideologist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proyectalo.ideologist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='interestRating',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='interested',
            field=models.ManyToManyField(through='proyectalo.InterestProjectBuilder', to='proyectalo.Builder'),
        ),
        migrations.CreateModel(
            name='TechnologyBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.IntegerField(choices=[(1, 'Immaterial'), (2, 'Tangible'), (3, 'Solid'), (4, 'Powerful')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectalo.builder')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proyectalo.technology')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectalo.builder')),
                ('ideologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectalo.ideologist')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proyectalo.project')),
            ],
        ),
        migrations.AddField(
            model_name='builder',
            name='technologies',
            field=models.ManyToManyField(through='proyectalo.TechnologyBuilder', to='proyectalo.Technology'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='proyectalo.Technology'),
        ),
    ]
